version: 2

# Ruby dependencies from / Gemfile
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

# Yarn dependencies in /client
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

# Yarn dependencies in / (used for build, scripts, etc)
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
