inherit_from:
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/master/rubocop/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true

AllCops:
  Exclude:
    - './app/dashboards/*'
    - './db/migrate/*'
    - './config/initializers/*'
    - './lib/tasks/*'

Rails/ApplicationController:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - acceptance
    - test
