version: '3'

services:
  site:
    image: node:12
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3000
      REACT_APP_STRIPE_API_KEY: pk_test_eQaIuCWvTwMYxTXFPXLho6n700kZpCcztx
      REACT_APP_URL_CREATE_ARTIST: 'https://www.ampled.com/create-an-artist-page'
      REACT_APP_URL_BLOG: 'https://ampled.com/zine'
      REACT_APP_URL_ABOUT: 'https://ampled.com/about'
  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - 1025:1025
      - 1080:1080
  db:
    image: postgres:10.4
    ports:
      - 5432:5432
    command: postgres -D /run/pgsql-10.4-data -c logging_collector=on
    volumes:
      - ./db/local_database_volume:/run/pgsql-10.4-data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      LOGGING_COLLECTOR: 'on'
      PGDATA: /run/pgsql-10.4-data
      POSTGRES_DB: ampled_web_development
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
