export const initialState = {
  authenticating: false,
  token: undefined,
  loggingOut: false,
  loggedOut: false,
  authModalOpen: false,
  modalPage: 'login',
  showSupportMessage: undefined,
  customLoginMessage: undefined,
  onModalCloseAction: undefined,
  redirectTo: undefined,
  artistName: undefined,
  artistSlug: undefined,
  error: undefined,
};
