export const routePaths = {
  root: '/',
  artists: '/artists/:id',
  slugs: '/artist/:slug',
  capsSlugs: '/(artist|support)/([a-zA-Z0-9\-]*[A-Z]+[a-zA-Z0-9\-]*)',
  support: '/support/:id',
  createPost: '/create_post/:id',
  connect: '/connect',
  home: '/home',
  passwordReset: '/users/password/edit',
  upload: '/upload',
  settings: '/settings',
  userDetails: '/user-details',
  noArtist: '/no_artist',
};
