export const routePaths = {
  root: '/',
  slugs: '/artist/:slug',
  editArtist: '/artist/:slug/edit',
  capsSlugs: '/(artist|support)/([a-zA-Z0-9-]*[A-Z]+[a-zA-Z0-9-]*)',
  support: '/support/:slug',
  createPost: '/create_post/:id',
  connect: '/connect',
  home: '/home',
  passwordReset: '/users/password/edit',
  forgotPassword: '/reset-password',
  upload: '/upload',
  settings: '/settings',
  userDetails: '/user-details',
  createArtist: '/create-artist',
  noArtist: '/no_artist',
};
