version: 2.1
commands:
  check-changed-files-or-halt:
    parameters:
      pattern:
        type: string
    steps:
      - run: git diff --name-only << pipeline.git.base_revision >> | egrep -q '<< parameters.pattern >>' || circleci step halt
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.6-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          # Needs to be set for production-like asset precompilation check
          SECRET_KEY_BASE: super-seekret
      - image: circleci/postgres:10.4-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ampled_web_test
          POSTGRES_PASSWORD: ''
      - image: circleci/redis
    resource_class: large
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout

      # Restore bundle cache, with fallbacks to increase the likeliness of a cache hit
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache

      # Bundle install dependencies and remove any unused gems
      - run: bundle install --path ./vendor/bundle --jobs=4 && bundle clean --force

      # Store bundle cache
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      # Setup database
      - run: bundle exec rake db:create db:schema:load db:migrate
      - run:
          name: Run Rails tests + Rubocop linting
          # Runs default rake tasks, as defined in Rakefile (includes spec, rubocop)
          command: bundle exec rake

      - run:
          name: Test production asset compilation
          command: RAILS_ENV=production bundle exec rake assets:precompile

      - run:
          name: Cypress tests
          command: yarn install && cd client && yarn install && cd .. && HOSTNAME=localhost yarn run integration-tests

      - store_artifacts:
          path: ~/circleci-demo-workflows/cypress/screenshots/

      # Steps below this line will only run if JavaScript/Typescript files have changed.
      - check-changed-files-or-halt:
          pattern: \.(js|ts|tsx|js|json)$
      - run:
          name: Run React tests
          command: npm run test-ci

workflows:
  version: 2
  build:
    jobs:
      - build
