version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}-

      - run:
          name: npm install yarn
          command: |
            YARN_VERSION=1.12.1
            if [[ $(yarn --version) != $YARN_VERSION ]]; then
              sudo npm install -g yarn@$YARN_VERSION;
              sudo chmod a+x /usr/local/bin/yarn
            fi

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run: yarn lint

      - run:
          name: yarn test
          command: yarn test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT: ./tmp/test-results/jest.xml

      - store_test_results:
          path: ./tmp/test-results
